Django_web_05/accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from . import views

app_name = 'accountapp'

urlpatterns = [
    path('', views.hello_world, name='hello_world'),
    path('create/', views.AccountCreateView.as_view(), name='create'),
    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('detail/<int:pk>', views.AccountDetailView.as_view(), name='detail'),

]

Django_web_05/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('accountapp.urls')),
]

Django_web_05/accountapp/models.py
from django.db import models


# Create your models here.
class HelloWorld(models.Model):
    text = models.CharField(max_length=255, null=False)

Django_web_05/accountapp/views.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render

# Create your views here.
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, DetailView

from accountapp.models import HelloWorld


def hello_world(request):
    if request.method == "POST":
        temp = request.POST.get('hello_world_input')
        new_hello_world = HelloWorld()
        new_hello_world.text = temp
        new_hello_world.save()

        hello_world_list = HelloWorld.objects.all()
        return HttpResponseRedirect(reverse('accountapp:hello_world'))

    else:
        hello_world_list = HelloWorld.objects.all()
        return render(request, 'accountapp/hello_world.html', context={'hello_world_list': hello_world_list})


#
# reverse => Use on Function Base View
# reverse_lazy => Use on Class Base View

class AccountCreateView(CreateView):
    model = User
    form_class = UserCreationForm
    success_url = reverse_lazy('accountapp:hello_world')
    template_name = 'accountapp/create.html'


class AccountDetailView(DetailView):
    model = User
    context_object_name = 'target_user'
    template_name = 'accountapp/detail.html'

Django_web_05/templates/accountapp/create.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
    <div class="account_create_form">
        <div>
            <h4>Sign up</h4>
        </div>
        <form class="account_create_form" action="{% url 'accountapp:create' %}" method="post">
            {% csrf_token %}
            {#            {{ form }}#}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-dark col-6 mt-3 rounded-pill">
        </form>

    </div>
{% endblock %}

Django_web_05/templates/accountapp/detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="main_area">
        <p>
            {{ target_user.date_joined }}
        </p>
        <h2>
            {{ target_user.username }}
        </h2>

    </div>
{% endblock %}

Django_web_05/templates/accountapp/hello_world.html
{% extends 'base.html' %}

{% block content %}
    <div class="main_area">
        <h1>Testing</h1>

        <form action="{% url 'accountapp:hello_world' %}" method="post">
            {% csrf_token %}
            <div>
                <label>
                    <input type="text" name="hello_world_input">
                </label>
            </div>

            <div>
                <input type="submit" class="btn btn-primary" value="POST">
            </div>
        </form>

        {% if hello_world_list %}
            {% for hello_world in hello_world_list %}
            <h1>
                {{ hello_world.text }}
            </h1>
            {% endfor %}
        {% endif %}

    </div>

{% endblock %}

Django_web_05/templates/accountapp/login.html
{% extends 'base.html' %}
{% load bootstrap5 %}


{% block content %}

    <div style="text-align: center; max-width: 500px; margin: 4rem auto">
        <div>
            <h4>Login</h4>
        </div>
        <div>
            <form action="" method="post">
                {% csrf_token %}
                {#                {{ form }}#}
                {% bootstrap_form form %}
                <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
            </form>
        </div>
    </div>

{% endblock %}

Django_web_05/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

{% include 'head.html' %}


<body>
{% include 'header.html' %}
<hr>
{% block content %}
{% endblock %}
<hr>


{% include 'footer.html' %}

<script src="{% static 'dist/js/bootstrap.js' %}"></script>
</body>
</html>

Django_web_05/templates/footer.html
<div class="footer_div">
    <div class="footer_top_div" >
        <span>공지사항</span>
        <span>제휴문의</span>
        <span>서비스 소개</span>

    </div>
    <div class="footer_bottom_div">
        <h6 class="folamatic_footer_logo">folamatic</h6>
    </div>
</div>

Django_web_05/templates/head.html
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>account app</title>

    {#   bootstrap css link   #}
    <link rel="stylesheet" type="text/css" href="{% static 'dist/css/bootstrap.css' %}">
    {#   My CSS   #}
    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">
    {#   Google Font Link    #}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Babylonica&display=swap" rel="stylesheet">
    {#  Font  #}
    {#  It doesn't work ...  #}
    <style>
        @font-face {
            font-family: 'GangwonEduAll';
            src: local('GangwonEduAll'),
            url("{% static 'fonts/GangwonEduAll.ttf' %}") format("truetype");
        }

        @font-face {
            font-family: 'GangwonEduPower';
            src: local('GangwonEduPower'),
            url("{% static 'fonts/GangwonEduPower.ttf' %}") format("truetype");
        }
    </style>
</head>

Django_web_05/templates/header.html
<div class="header_div">
    <div><h1 class="Folamatic_main_logo">Folamatic</h1></div>
    <div>
        <span class="mx-3">nav1</span>
        <span class="mx-3">nav2</span>
        <span class="mx-3"> nav3</span>
        {#    LoginView, LogoutView Redirect Order   #}
        {# 1. next   #}
        {# 2. LOGIN_REDIRECT_URL (setting.py)   #}
        {# 3. default   #}
        {% if not user.is_authenticated %}
            <a href="{% url 'accountapp:login' %}?next={{ request.path }}">
                <span class="mx-3">login</span>
            </a>
            <a href="{% url 'accountapp:create' %}"><span class="mx-3">signup</span></a>
        {% else %}
            <a href="{% url 'accountapp:detail' pk=user.pk %}">
                <span class="mx-3">My Page</span>
            </a>
            <a href="{% url 'accountapp:logout' %}?next={{ request.path }}">
                <span class="mx-3">logout</span>
            </a>

        {% endif %}


    </div>

</div>