Django_web_03/Django_web_03/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
    path('myWeb/', include('myWeb.urls')),
    path('mySecondWeb/', include('my_second_web.urls')),
    path('pyfo/', include('pyfo.urls')),
    path('', include('myWeb.urls')),
]


# url 패턴은 setting.py INSTALLED_APPS 에 설정하지 않더라도 작동함

Django_web_03/myWeb/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index')
]

Django_web_03/my_second_web/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index')
]

Django_web_03/polls/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # ex: /polls/
    path('', views.index, name='index'),

    path('index_old/', views.index_old, name='index'),

    # ex: /polls/5/
    path('<int:question_id>/', views.detail, name='detail'),

    # ex: /polls/5/result/
    path('<int:question_id>/results/', views.results, name='results'),

    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),

    path('page_<int:page_num>/', views.page, name='pages'),
]

Django_web_03/pyfo/urls.py
from django.urls import path

from . import views

app_name = 'pyfo'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    path('question/create/', views.question_create, name='question_create')
]

Django_web_03/polls/models.py
from django.db import models
from django.utils import timezone
import datetime


# Create your models here.

# question_text, pub_date ==> DB 의 컬럼명
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

Django_web_03/pyfo/models.py
from django.db import models


# Create your models here.


class Question(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()

    def __str__(self):
        return self.subject


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()

    def __str__(self):
        return self.question

Django_web_03/pyfo/forms.py
from django import forms
from pyfo.models import Question, Answer


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['subject', 'content']

        # Django form 에 model 컬럼 표시 내용 변경
        labels = {
            'subject': '제목',
            'content': '내용'
        }

        # 세밀한 html 디자인을 위해 위젯 주석처리
        #
        # # Django form 에 태그 속성 부여
        # widgets = {
        #     'subject': forms.TextInput(attrs={
        #         'class': 'form-control'
        #     }),
        #     'content': forms.Textarea(attrs={
        #         'class': 'form-control',
        #         'rows': 10
        #     })
        # }


class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
            'content': '답변내용'
        }

Django_web_03/myWeb/views.py
from django.shortcuts import render
from django.http import HttpResponse


# Create your views here.
def index(request):
    return HttpResponse("Hello again. This is myWeb.")

Django_web_03/my_second_web/views.py
from django.http import HttpResponse
from django.shortcuts import render


# Create your views here.

def index(request):
    return HttpResponse("Hello again, This is my_second_web")

Django_web_03/polls/views.py
from django.shortcuts import render

# Create your views here.

from django.http import HttpResponse
from .models import Question
from django.template import loader


def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')
    context = {
        'latest_question_list': latest_question_list
    }
    return render(request, 'polls/index.html', context)


def index_old_2(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    template = loader.get_template('polls/index.html')
    context = {
        'latest_question_list': latest_question_list,
    }
    return HttpResponse(template.render(context, request))


def index_old(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    output = ' <br>'.join([q.question_text for q in latest_question_list])
    return HttpResponse(output)


def detail(request, question_id):
    return HttpResponse("You're looking at question %s." % question_id)


def results(request, question_id):
    response = "You're looking at the result of question %s."
    return HttpResponse(response % question_id)


def vote(request, question_id):
    return HttpResponse("You're voting on question %s" % question_id)


def page(request, page_num):
    pages = 'polls/pages_/page_' + str(page_num) + '.html'
    print(pages)
    return render(request, pages)

Django_web_03/pyfo/views.py
from django.core.paginator import Paginator
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from .forms import QuestionForm, AnswerForm
from .models import Question, Answer


# Create your views here.


def index(request):
    """
    pyfo 목록 출력
    """

    # input parameter
    page = request.GET.get('page', 1)

    # Get all Question object
    question_list = Question.objects.order_by('-create_date')

    # Paginator
    per_page = 20
    paginator = Paginator(question_list, per_page)
    page_obj = paginator.get_page(page)

    # Get max page index
    max_index = len(paginator.page_range)

    context = {
        'question_page_obj': page_obj,
        'max_index': max_index,
    }
    return render(request, 'pyfo/question_list.html', context)


def detail(request, question_id):
    """
    pyfo 내용 출력
    """
    # 객체를 그냥 읽어오는 방법
    # question = Question.objects.get(id=question_id)

    # DB 에서 불러올 객체가 없을 경우 404에러를 띄우는 방법
    question = get_object_or_404(Question, pk=question_id)

    context = {'question': question}
    return render(request, 'pyfo/question_detail.html', context)


def answer_create(request, question_id):
    """
    pyfo 답변 등록, Answer 모델 이용
    """
    question = get_object_or_404(Question, pk=question_id)

    if request.method == 'POST':
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            return redirect('pyfo:detail', question_id=question.id)
    else:
        form = AnswerForm()
    context = {
        'question': question,
        'form': form,
    }
    return render(request, 'pyfo/question_detail.html', context)


# 질문 생성 (QuestionForm)
def question_create(request):
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.create_date = timezone.now()
            question.save()
            return redirect('pyfo:index')
    else:
        form = QuestionForm()

    context = {'form': form}
    return render(request, 'pyfo/question_form.html', context)


# 질문 삭제
# def question_delete(request):


#
# 사용하지 않음 (참고용 코드)
def answer_create_old_01(request, question_id):
    """
    pyfo 답변 등록
    """

    question = get_object_or_404(Question, pk=question_id)
    question.answer_set.create(content=request.POST.get('content'), create_date=timezone.now())
    return redirect('pyfo:detail', question_id=question.id)


# 사용하지 않음 (참고용 코드)
def answer_create_old_02(request, question_id):
    """
    pyfo 답변등록, Answer 모델 이용
    :param request: Question object
    :param question_id: question.id
    :return: redirect(pyfo:detail, question_id=question.id)
    """
    question = get_object_or_404(Question, pk=question_id)
    answer = Answer(question=question, content=request.POST.get('content'), create_date=timezone.now())
    answer.save()
    return redirect('pyfo:detail', question_id=question.id)

Django_web_03/templates/polls/index.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>

{% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
            <li>
                <a href="/polls/{{ question.id }}/">
                    {{ question.question_text }}
                </a>
            </li>
        {% endfor %}
    </ul>
{% else %}
    <p>
        No polls are available.
    </p>
{% endif %}

</body>
</html>

Django_web_03/templates/polls/pages_/page_1.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>polls page</title>
</head>
<body>
This is polls page_1.html
</body>
</html>

Django_web_03/templates/polls/pages_/page_2.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>polls page</title>
</head>
<body>
This is polls page_2.html
</body>
</html>

Django_web_03/templates/polls/pages_/page_3.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>polls page</title>
</head>
<body>
This is polls page_3.html
</body>
</html>

Django_web_03/templates/pyfo/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>pyfo</title>

    {# Bootstrap Css #}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/dist/css/bootstrap.css' %}">
</head>


<body>

{# nav-var start #}
<nav class="container navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        Dropdown
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="#">Action</a></li>
                        <li><a class="dropdown-item" href="#">Another action</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled">Disabled</a>
                </li>
            </ul>
            <form class="d-flex">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>
{# nav-var end #}

{% block body_content %}
{% endblock %}



<script src="{% static 'bootstrap/dist/js/bootstrap.js' %}"></script>
</body>
</html>

Django_web_03/templates/pyfo/old/question_form_old.html
{% extends 'pyfo/base.html' %}

{% block body_content %}
    <div class="container">
        <h5 class="my-5 border-bottom pb-2">질문 등록</h5>
        <form method="post" class="my-3">
            {% csrf_token %}
            {#  Error handling code Start  #}
            {% if form.errors %}
                <div class="alert alert-danger" role="alert">
                    {% for field in form %}
                        {% if field.errors %}
                            <strong>{{ field.errors }}</strong>
                        {% endif %}

                    {% endfor %}
                </div>
            {% endif %}
            {#  Error handleing code End   #}

            {#  Question Create Form Start  #}
            <div class="form-group">
                <label for="subject">제목</label>
                <input
                        type="text"
                        class="form-control"
                        name="subject"
                        id="subject"
                        value="{{ form.subject.value|default_if_none:'' }}">
            </div>


            <div class="form-group">
                <label for="content">내용</label>
                <textarea
                        name="content"
                        id="content"
                        rows="10"
                        class="form-control"
                >
                    {{ form.content.value|default_if_none:'' }}

                </textarea>
            </div>
            <hr>
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">저장하기</button>
        </form>
    </div>
{% endblock %}

Django_web_03/templates/pyfo/old/question_list_old.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>pyfo</title>
</head>
<body>
<h1>Pyfo Index.html</h1>
{% if question_list %}
    <ul>
        {% for question in question_list %}

            <li><a href="/pyfo/{{ question.id }}/">Question {{ forloop.counter }}. {{ question.subject }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>There's no question</p>
{% endif %}
</body>
</html>

Django_web_03/templates/pyfo/old/question_list_old_2.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>pyfo</title>

    {# Bootstrap Css #}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/dist/css/bootstrap.css' %}">
</head>


<body>

{# nav-var start #}
<nav class="container navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        Dropdown
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="#">Action</a></li>
                        <li><a class="dropdown-item" href="#">Another action</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled">Disabled</a>
                </li>
            </ul>
            <form class="d-flex">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>
{# nav-var end #}


<div class="container my-3">

    <table class="table">
        <thead>
        <tr class="bg-info">
            <th>번호</th>
            <th>제목</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if question_list %}
            {% for question in question_list %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td><a href="{% url 'pyfo:detail' question.id %}">{{ question.subject }}</a></td>
                    <td>{{ question.create_date }}</td>
                </tr>
            {% endfor %}
        {% endif %}
        </tbody>

    </table>
</div>

<hr></hr>
{% if question_list %}
    <ul>
        {% for question in question_list %}
            <li><a href="{% url 'pyfo:detail' question.id %}">Question {{ question.id }}. {{ question.subject }}</a>
            </li>
        {% endfor %}
    </ul>
{% else %}
    <p>There's no question</p>
{% endif %}




<script src="{% static 'bootstrap/dist/js/bootstrap.js' %}"></script>
</body>
</html>

Django_web_03/templates/pyfo/question_detail.html
{% extends 'pyfo/base.html' %}

{% block body_content %}
    <div class="container my-3">
        {# Question contents area #}
        <div>
            {% if question %}

                <h2>{{ question.subject }}</h2>
                <span> 작성 시각: {{ question.create_date }}</span>
                <br>
                <div class="card my-3">
                    <div class="card-body">
                        <div class="card-text" style="white-space: pre-line">
                            {{ question.content }}
                        </div>
                        <div class="d-flex justify-content-end">
                            {#   d-flex : 자기자신은 block, 자식은 in-line 으로 만들어준다   #}
                            {#   justif-content-? 자식요소들의 정렬 기준 #}
                            {#   : start, end, center, between(양쪽 요소를 좌우에 붙이고 안쪽 요소들을 균일한 간격으로 배치), around(전체요소를 균일한 간격으로 배치)   #}
                            {{ question.create_date }}
                        </div>
                    </div>
                </div>
                <form action=""></form>
            {% else %}
                <h3>No question number</h3>
            {% endif %}
        </div>

        {# Answer content area #}
        <div>
            <h5 class="border-bottom my-3 py-3">
                {{ question.answer_set.count }}개의 답변이 있습니다.
            </h5>
            {% for answer in question.answer_set.all %}
                <div class="card my-3">
                    <div class="card-body">
                        <div class="card-text" style="white-space: pre-line">
                            {{ answer.content }}
                        </div>
                        <div class="d-flex justify-content-end">
                            <div class="badge bg-light text-dark">
                                {{ answer.create_date }}
                            </div>
                        </div>

                    </div>

                </div>
            {% endfor %}


        </div>

        <hr>
        {# Reply contents area #}
        <div>
            <form action="{% url 'pyfo:answer_create' question.id %}" method="post" class="my-3">
                {% csrf_token %}
                {% if form.errors %}
                    <div class="alert alert-danger" role="alert">
                        {% for field in form %}
                            {% if field.errors %}
                                <strong>{{ field.label }}</strong>
                                {{ field.errors }}
                                ( 내용은 비워둘 수 없습니다 )
                            {% endif %}
                        {% endfor %}
                    </div>
                {% endif %}
                <div class="form-floating">
                    <label for="content"></label>
                    <textarea name="content" id="content" class="form-control my-3" style="height: 10rem"></textarea>
                </div>
                <input type="submit" value="답변 등록" class="btn btn-primary">

            </form>
        </div>


        <p>
            <a href="{% url 'pyfo:index' %}">질문 리스트 페이지로 돌아가기</a>
        </p>

    </div>
{% endblock %}

Django_web_03/templates/pyfo/question_form.html
{% extends 'pyfo/base.html' %}

{% block body_content %}
    <div class="container">
        <h5 class="my-5 border-bottom pb-2">질문 등록</h5>
        <form method="post" class="my-3">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">저장하기</button>
        </form>
    </div>
{% endblock %}

Django_web_03/templates/pyfo/question_list.html
{% extends 'pyfo/base.html' %}
{% load pyfo_filter %}


{% block body_content %}
    <div class="container my-3">

        <table class="table table-hover table-sm">


            <thead>
            <tr class="bg-info">
                <th>번호</th>
                <th>제목</th>
                <th>작성일시</th>
            </tr>
            </thead>
            <tbody>
            {% if question_page_obj %}
                {% for question in question_page_obj %}
                    <tr>
                        {# paginator.count == The numboer of whole pages (305, 305, 305 ...)                                            #}
                        {# question_page_obj.start_index == Start index of thrown object that has paginated pages (1, 11, 21, 31 ...)   #}
                        {# forloop.counter0 == Loop counter in for clause (0, 1, 2, 3 ...)                                              #}
                        <td>{{ question_page_obj.paginator.count|sub:question_page_obj.start_index|sub:forloop.counter0|add:1 }}</td>
                        <td>
                            <a class="text-decoration-none text-dark" href="{% url 'pyfo:detail' question.id %}">
                                {{ question.subject }}
                                {% if question.answer_set.count > 0 %}
                                    <span class="text-danger small ms-2">
                                        {{ question.answer_set.count }}
                                    </span>

                                {% endif %}
                            </a>
                        </td>
                        <td>{{ question.create_date }}</td>
                    </tr>
                {% endfor %}
            {% endif %}
            </tbody>


        </table>
        <div class="container my-3">
            <a class="btn btn-primary bg-secondary opacity-75" href="{% url 'pyfo:question_create' %}">질문 등록하기</a>
        </div>


        {# Paging Start #}
        <ul class="pagination justify-content-center">

            {# Previous Page #}
            {% if question_page_obj.has_previous %}

                <li class="page-item bg-secondary">
                    <a class="page-link text-dark" href="?page=1">처음</a>
                </li>
                <li class="page-item bg-secondary">
                    <a class="page-link text-dark" href="?page={{ question_page_obj.previous_page_number }}">이전</a>
                </li>

            {% else %}
                <li class="page-item disabled">
                    <a class="page-link" tabindex="-1" aria-disabled="true" href="#">처음</a>
                </li>
                <li class="page-item disabled">
                    <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
                    {# TAG : tabindex="-1" -> tab 키를 눌렀을때 반응하지 않도록 만듬 #}
                </li>
            {% endif %}


            {# Page list #}
            {% for page_number in question_page_obj.paginator.page_range %}


                {# Page list range condition #}
                {# -5 ~ +5 사이 값일 경우에만 #}
                {% if page_number >= question_page_obj.number|add:-5 and page_number <= question_page_obj.number|add:5 %}

                    {% if page_number == question_page_obj.number %}
                        <li class="page-item active" aria-current="page">
                            {# class="active" -> 선택된 페이지의 배경색 강조 #}
                            {# aria- 태그는 모두 저시력자의 읽기 도구와 관련된 태그임 #}
                            <a class="page-link bg-secondary opacity-75" href="?page={{ page_number }}">
                                {{ page_number }}
                            </a>
                        </li>
                    {% else %}
                        <li class="page-item">
                            <a class="page-link text-secondary" href="?page={{ page_number }}">
                                {{ page_number }}
                            </a>
                        </li>
                    {% endif %}

                {% endif %}
                {# Page list range condition end potint is here #}


            {% endfor %}
            {# Page list end #}


            {# Next page #}
            {% if question_page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link text-dark" href="?page={{ question_page_obj.next_page_number }}">다음</a>
                </li>
                <li class="page-item">
                    <a class="page-link text-dark" href="?page={{ max_index }}">마지막</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link text-dark" tabindex="-1" aria-disabled="true" href="#">다음</a>
                    {# aria-disabled="true" 저시력자를 위한 읽기 도구가 (a) 태그를 읽지 않도록 명시함 #}
                </li>
                <li class="page-item disabled">
                    <a class="page-link text-dark" tabindex="-1" aria-disabled="true" href="#">마지막1</a>
                </li>
            {% endif %}
        </ul>
        {# Paging End #}

    </div>

{% endblock %}